### ISSUE TITLE
CI/CD SemVer is not Used in IaC

### ISSUE THREAD

**Issue by jamescrowley321** [sourcefuse/backstage#114]
The IaC needs the SemVer passed to it instead of the branch name

```
                  ~ image                  = "***.dkr.ecr.us-east-1.amazonaws.com/sourcefuse-backstage:0.1.0" -> "***.dkr.ecr.us-east-1.amazonaws.com/sourcefuse-backstage:main"
```

**Comment by tsaucier-sf** [comment]
When we are doing git tag and the workflow triggers the next workflow to do the docker build and push steps, it isn't picking up the new tag and is using the brach ref. This needs to be modified to pull the latest tag for the commit being built. If there is no tag, it should default to the branch (maybe??).
