### ISSUE TITLE
Compiled with problems

### ISSUE THREAD

**Issue by Tyagi-Sunny** [sourcefuse/backstage#126]
**Describe the bug**
× ERROR in ../../node_modules/swagger-ui-react/node_modules/react-redux/dist/react-redux.mjs 1097:18-45
![Screenshot from 2024-01-16 19-33-02](https://github.com/sourcefuse/backstage/assets/107617248/8f932058-8d6a-416b-b5a4-22c089d4cc53)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Tyagi-Sunny** [comment]
This issue typically occurs when updating the backstage version within the application. However, there's no need to update the version at the moment. Therefore, you can close it.
cc: @jamescrowley321 @sadarunnisa-sf @Yogi-Vishwas

**Comment by sadarunnisa-sf** [comment]
Thanks @Tyagi-Sunny . If in future , we would be updating backstage version, this issue would arise. Kindly update here as well as in readme which react package to update to resolve this issue.

**Comment by Tyagi-Sunny** [comment]
this issue can be solve by updating swagger-ui-react package. detailed explanation can be seen here https://github.com/backstage/backstage/issues/22142
